Repository talview/moodle-local_proview, pull requests merged in 2024-08, with the labels that each got.

#96 Release/v3.3.3
  templates/tracker.mustache
  version.php
Labels: Bug fix, Enhancement, Review effort [1-5]: 2

#97 Merge to 3.3.4
  templates/tracker.mustache
  version.php
Labels: Bug fix, Enhancement, Review effort [1-5]: 2

#95 [94] [FIX] Close (X) icon is overriding the candidate id on playback view
  templates/tracker.mustache
  version.php
Labels: Bug fix, Review effort [1-5]: 2

#99 Release/v3.3.4 to Matser
  templates/tracker.mustache
  version.php
Labels: Enhancement, Review effort [1-5]: 2, bug_fix

#100 Provision secure browser without proctoring
  classes/local/api/tracker.php
  classes/local/injector.php
  version.php
Labels: Enhancement, bug_fix, Review effort [1-5]: 4
